/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.compilers.lexer;
import java.util.List;

public class App {
    public static String programa =
            "x = 3;\n" +
                    "ya = 22+4-10;\n" +
                    "print(x2);";


    public static void main(String[] args) {
        LexerManual lexer = new LexerManual(App.programa);
        List<Token> tokens = lexer.tokens();
        for (Token t : tokens) {
            System.out.println(t);
        }
    }
}
